services:
  cypress:
    image: cypress/included:cypress-12.17.3-node-18.16.0-chrome-114.0.5735.133-1-ff-114.0.2-edge-114.0.1823.51-1
    networks:
      - hmpps
    volumes:
      - ./:/e2e
    working_dir: /e2e
    environment:
      CYPRESS_BASE_URL: http://community-payback-assessment-ui:3000
      CYPRESS_AUTH_URL: http://hmpps-auth:9090/auth/oauth/token?grant_type=client_credentials&username=foobar

volumes:
  test_results:
